name: third yml file

on:
  push:
    branches:
      - main



jobs:
  third-job:
    runs-on: ubuntu-latest
    steps:
    

      - name: step 2 check environemt variable 
        run: | 
          whoami
      - name: my name
        run: echo "hello world there would ne"    


        